# ================================================================================
# ACTC-BalcaoDigital.py
# Balcão Digital (E-Redes) data pipeline - adapted for Colab, local, Flask and Render
# ================================================================================


import os
import sys
import datetime
import json
import socket
import smtplib
import ssl
import io
import re
import unicodedata
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


import pandas as pd
import requests
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload


import clts_pcp as clts


from services.file_audit import (
    prepare_file_audit,
    file_hash_exists,
    insert_file_audit_row,
)


print("... imports done.")



# ================================================================================
# detect environment: colab, render or local
# ================================================================================
def detect_environment():
    if "COLAB_RELEASE_TAG" in os.environ:
        return "colab"
    elif "RENDER" in os.environ:
        return "render"
    else:
        return "local"



# ================================================================================
# secret loaders - unified interface for all environments
# ================================================================================
def get_secret(name):
    return os.getenv(name)



def get_secret_json(name):
    if env == "colab":
        return json.loads(userdata.get(name))
    elif env == "render":
        with open(f"/etc/secrets/{name}") as f:
            return json.load(f)
    else:
        with open(f"secrets/{name}") as f:
            return json.load(f)



# ================================================================================
# fetch existing IDs from CrateDB / TiDB in batches to avoid statement_max_length limits
# ================================================================================
def fetch_existing_ids_in_batches(cursor, table, all_ids, batch_size=500):
    existing = set()


    if not all_ids:
        return existing


    is_tidb = cursor.__class__.__module__.lower().startswith("pymysql")


    for i in range(0, len(all_ids), batch_size):
        batch = all_ids[i:i + batch_size]
        placeholders = ", ".join(["%s" if is_tidb else "?" for _ in batch])
        sql = f"SELECT id FROM {table} WHERE id IN ({placeholders})"
        cursor.execute(sql, tuple(batch))
        existing.update(row[0] for row in cursor.fetchall())


    return existing



# ================================================================================
# append execution summary rows into the same notification table generated by clts
# ================================================================================
def inject_summary_into_existing_notification_table(toem, summary_rows_html):
    try:
        lower_toem = toem.lower()
        tbody_close_idx = lower_toem.rfind("</tbody>")
        table_close_idx = lower_toem.rfind("</table>")


        if tbody_close_idx != -1:
            return toem[:tbody_close_idx] + summary_rows_html + toem[tbody_close_idx:]
        elif table_close_idx != -1:
            return toem[:table_close_idx] + summary_rows_html + toem[table_close_idx:]
        else:
            return toem + summary_rows_html
    except Exception:
        return toem + summary_rows_html



# ================================================================================
# build summary rows using the same table structure already used in notification
# ================================================================================
def build_summary_rows_html(
    files_found_count,
    files_downloaded_count,
    files_skipped_by_hash_count,
    files_to_process_count,
    files_parsed_count,
    row_level_check_executed,
    balcao_digital_rows_checked,
    balcao_digital_rows_inserted,
    balcao_digital_rows_skipped,
    balcao_consumo_rows_checked,
    balcao_consumo_rows_inserted,
    balcao_consumo_rows_skipped
):
    rows = []


    rows.append("<tr><td colspan='3'><b>Execution summary</b></td></tr>")
    rows.append(f"<tr><td>Files found</td><td>{files_found_count}</td><td></td></tr>")
    rows.append(f"<tr><td>Files downloaded</td><td>{files_downloaded_count}</td><td></td></tr>")
    rows.append(f"<tr><td>Files skipped by hash</td><td>{files_skipped_by_hash_count}</td><td></td></tr>")
    rows.append(f"<tr><td>Files sent to parsing</td><td>{files_to_process_count}</td><td></td></tr>")
    rows.append(f"<tr><td>Files parsed successfully</td><td>{files_parsed_count}</td><td></td></tr>")
    rows.append(f"<tr><td>Rows inserted @ balcao_digital</td><td>{balcao_digital_rows_inserted}</td><td></td></tr>")
    rows.append(f"<tr><td>Rows inserted @ balcao_digital_consumo</td><td>{balcao_consumo_rows_inserted}</td><td></td></tr>")


    return "\n".join(rows)



# ================================================================================
# helper: open database connection from dblist entry
# ================================================================================
def open_database_connection(user, db):
    dbcreds = get_secret_json(f"{user}-{db}.json")


    if dbcreds.get("dbms") == "crate" or db == "crate":
        from crate import client
        print("... connecting to crate database...")
        connection = client.connect(
            dbcreds["dest_host"],
            username=dbcreds["username"],
            password=dbcreds["password"],
            verify_ssl_cert=True
        )
        cursor = connection.cursor()
        return connection, cursor, "crate", dbcreds


    elif dbcreds.get("dbms") in ("sql", "sql_tls") or db == "tidb":
        import pymysql
        print("... connecting to tidb database...")
        connection = pymysql.connect(
            host=dbcreds.get("host", dbcreds.get("dest_host")),
            port=int(dbcreds.get("port", 4000)),
            user=dbcreds["username"],
            password=dbcreds["password"],
            database=dbcreds["database"],
            autocommit=False,
            charset="utf8mb4",
            cursorclass=pymysql.cursors.Cursor
        )
        cursor = connection.cursor()
        return connection, cursor, "tidb", dbcreds


    else:
        raise ValueError(f"Unsupported DBMS for Balcão Digital: {dbcreds.get('dbms')}")



# ================================================================================
# helper: normalize raw column names
# ================================================================================
def normalize_column_name(value):
    value = "" if value is None else str(value)
    value = value.strip().lower()
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("utf-8")
    value = re.sub(r"[\(\)\[\]\{\}]", " ", value)
    value = re.sub(r"[-_/]", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value



# ================================================================================
# helper: build normalized column map
# ================================================================================
def build_normalized_column_map(columns):
    return {col: normalize_column_name(col) for col in columns}



# ================================================================================
# helper: find first raw column matching one exact normalized candidate
# ================================================================================
def find_first_exact_column(colmap, candidates):
    for raw, norm in colmap.items():
        if norm in candidates:
            return raw
    return None



# ================================================================================
# helper: find first raw column containing one of the normalized fragments
# ================================================================================
def find_first_column_contains(colmap, fragments):
    for raw, norm in colmap.items():
        for fragment in fragments:
            if fragment in norm:
                return raw
    return None



# ================================================================================
# helper: parse one file once and classify it as type A or B
# ================================================================================
def parse_balcao_file(filename, buffer):
    cpe = filename.split("_")[1]


    file_type = None
    skip = None
    cols = []


    # auto-detect skiprows and file type
    for sr in [8, 9]:
        buffer.seek(0)
        df_peek = pd.read_excel(buffer, skiprows=sr, header=0, nrows=0)
        cols = df_peek.columns.tolist()
        colmap = build_normalized_column_map(cols)


        data_col = find_first_exact_column(colmap, {"data"})
        hora_col = find_first_exact_column(colmap, {"hora"})


        consumo_col = find_first_column_contains(colmap, [
            "consumo registado"
        ])


        potencia_ativa_col = find_first_column_contains(colmap, [
            "potencia ativa saldo",
            "potencia ativa"
        ])


        if data_col and hora_col and consumo_col:
            file_type = "B"
            skip = sr
            break
        elif data_col and hora_col and potencia_ativa_col:
            file_type = "A"
            skip = sr
            break


    if file_type is None:
        raise ValueError(f"Unknown file type — columns: {cols}")


    buffer.seek(0)
    df = pd.read_excel(buffer, skiprows=skip, header=0)


    raw_cols = df.columns.tolist()
    colmap = build_normalized_column_map(raw_cols)


    data_col = find_first_exact_column(colmap, {"data"})
    hora_col = find_first_exact_column(colmap, {"hora"})


    if not data_col or not hora_col:
        raise ValueError(f"Missing required Data/Hora columns — columns: {raw_cols}")


    df = df.dropna(subset=[data_col, hora_col])
    df["tstamp"] = pd.to_datetime(
        df[data_col].astype(str) + " " + df[hora_col].astype(str),
        format="%Y/%m/%d %H:%M",
        errors="coerce"
    )
    df = df.dropna(subset=["tstamp"])
    df["cpe"] = cpe
    df["id"] = cpe + "_" + df["tstamp"].dt.strftime("%Y%m%d%H%M")


    if file_type == "B":
        estado_col = find_first_exact_column(colmap, {"estado"})
        consumo_col = find_first_column_contains(colmap, [
            "consumo registado"
        ])


        if consumo_col is None:
            raise ValueError(f"Missing consumo column — columns: {raw_cols}")


        df["consumo_kw"] = pd.to_numeric(df[consumo_col], errors="coerce")


        if estado_col is not None:
            df["estado"] = df[estado_col]
        else:
            df["estado"] = None


        df = df[["id", "tstamp", "cpe", "consumo_kw", "estado"]]


    else:
        potencia_ativa_col = find_first_column_contains(colmap, [
            "potencia ativa saldo",
            "potencia ativa"
        ])
        potencia_reativa_ind_col = find_first_column_contains(colmap, [
            "potencia reativa indutiva"
        ])
        potencia_reativa_cap_col = find_first_column_contains(colmap, [
            "potencia reativa capacitiva"
        ])


        if potencia_ativa_col is None:
            raise ValueError(f"Missing potencia ativa column — columns: {raw_cols}")


        df["potencia_ativa"] = pd.to_numeric(df[potencia_ativa_col], errors="coerce")


        if potencia_reativa_ind_col is not None:
            df["potencia_reativa_ind"] = pd.to_numeric(df[potencia_reativa_ind_col], errors="coerce")
        else:
            df["potencia_reativa_ind"] = None


        if potencia_reativa_cap_col is not None:
            df["potencia_reativa_cap"] = pd.to_numeric(df[potencia_reativa_cap_col], errors="coerce")
        else:
            df["potencia_reativa_cap"] = None


        df = df[["id", "tstamp", "cpe", "potencia_ativa", "potencia_reativa_ind", "potencia_reativa_cap"]]


    return file_type, df, cpe



# ================================================================================
# helper: build insert values for one table
# ================================================================================
def build_values_to_insert(table, df_insert, existing_ids):
    values_to_insert = []
    skipped = 0
    skipped_list = []


    for _, row in df_insert.iterrows():
        if row["id"] in existing_ids:
            skipped += 1
            skipped_list.append(str(row["tstamp"]))
            continue


        if table == "balcao_digital":
            values_to_insert.append((
                row["id"],
                row["tstamp"].strftime("%Y-%m-%d %H:%M:%S"),
                row["cpe"],
                None if pd.isna(row["potencia_ativa"]) else float(row["potencia_ativa"]),
                None if pd.isna(row["potencia_reativa_ind"]) else float(row["potencia_reativa_ind"]),
                None if pd.isna(row["potencia_reativa_cap"]) else float(row["potencia_reativa_cap"])
            ))
        else:
            values_to_insert.append((
                row["id"],
                row["tstamp"].strftime("%Y-%m-%d %H:%M:%S"),
                row["cpe"],
                None if pd.isna(row["consumo_kw"]) else float(row["consumo_kw"]),
                None if pd.isna(row["estado"]) else str(row["estado"])
            ))


    return values_to_insert, skipped, skipped_list



# ================================================================================
# helper: get SQL insert statement per table / engine
# ================================================================================
def get_insert_sql(table, db_engine):
    if table == "balcao_digital":
        sql = (
            "INSERT INTO balcao_digital "
            "(id, tstamp, cpe, potencia_ativa, potencia_reativa_ind, potencia_reativa_cap) "
            "VALUES (?, ?, ?, ?, ?, ?)"
        )
    else:
        sql = (
            "INSERT INTO balcao_digital_consumo "
            "(id, tstamp, cpe, consumo_kw, estado) "
            "VALUES (?, ?, ?, ?, ?)"
        )


    if db_engine == "tidb":
        sql = sql.replace("?", "%s")


    return sql



# ================================================================================
# pipeline
# ================================================================================
def run_pipeline(run_params=None):
    global env, hostname, ip, user, script, channel, destination, verbose, send_mail, email_addresses, context


    env = detect_environment()
    print("Running in:", env)


    if env == "colab":
        from google.colab import userdata  # type: ignore
        import ipynbname  # type: ignore
    elif env == "local":
        from dotenv import load_dotenv
        load_dotenv()


    tstart = clts.getts()
    clts.elapt.clear()


    DEFAULT_PARAMS = {
        "verbose": True,
        "destination": "dblist",
        "send_mail": True,
        "email_addresses": ["acatarinatc@gmail.com"],
    }


    if run_params:
        if run_params.get("start_date"):
            DEFAULT_PARAMS["start_date"] = run_params["start_date"]
        if run_params.get("days_back") is not None:
            DEFAULT_PARAMS["days_back"] = int(run_params["days_back"])


    hostname = socket.gethostname()
    ip = requests.get("https://api.ipify.org").text
    print("Server name:", hostname, "Public IP Address:", ip)


    if env == "colab":
        notebookname = requests.get("http://172.28.0.12:9000/api/sessions").json()[0]["name"]
        user = notebookname.split("-")[0]
        script = ipynbname.name()
    else:
        user = os.getenv("USER", "ACTC")
        script = os.path.basename(__file__)


    channel = "balcao_digital"
    destination = DEFAULT_PARAMS["destination"]
    verbose = DEFAULT_PARAMS["verbose"]
    send_mail = DEFAULT_PARAMS["send_mail"]
    email_addresses = DEFAULT_PARAMS["email_addresses"]


    context = f"{hostname} ({ip}) | {user} | {channel} | {script} | {destination}"
    clts.setcontext(context)
    if verbose:
        print("context:", context)
    clts.elapt[f"Environment detected: {env}"] = clts.deltat(tstart)


    # ================================================================================
    # derive date window from run_params
    # ================================================================================
    start_date_str = DEFAULT_PARAMS.get("start_date", datetime.date.today().strftime("%Y-%m-%d"))
    days_back = DEFAULT_PARAMS.get("days_back", 0)
    start_date = datetime.datetime.strptime(str(start_date_str), "%Y-%m-%d").date()
    window_start = start_date - datetime.timedelta(days=days_back)
    window_end = start_date
    print(f"Date window: {window_start} → {window_end}")


    # ================================================================================
    # connect to google drive and list files in folder
    # ================================================================================
    FOLDER_ID = os.getenv("BALCAO_SHARED_FOLDER_ID")


    creds_raw = get_secret_json("ACTC-DriveCredentials.json")
    credentials = service_account.Credentials.from_service_account_info(
        creds_raw,
        scopes=["https://www.googleapis.com/auth/drive.readonly"]
    )
    service = build("drive", "v3", credentials=credentials)
    print("Connected to Google Drive.")


    # list all files in folder (excluding trashed), supporting shared drives
    response = service.files().list(
        q=f"'{FOLDER_ID}' in parents and trashed = false",
        fields="files(id, name, size, modifiedTime)",
        supportsAllDrives=True,
        includeItemsFromAllDrives=True
    ).execute()


    all_files = response.get("files", [])
    clts.elapt["Balcão Digital files list retrieved from Google Drive"] = clts.deltat(tstart)
    print(f"Total files found in folder: {len(all_files)}")


    # ── filter files by date window using filename: Consumos_<CPE>_<YYYYMMDD>HHMMSS.xlsx ──
    files = []
    for f in all_files:
        try:
            date_str = f["name"].split("_")[2][:8]
            file_date = datetime.datetime.strptime(date_str, "%Y%m%d").date()
            if window_start <= file_date <= window_end:
                files.append(f)
        except Exception:
            pass


    clts.elapt[f"Files identified ({window_start} → {window_end}, {days_back} days back)"] = clts.deltat(tstart)
    print(f"Files in window ({window_start} → {window_end}): {len(files)} / {len(all_files)}")
    for f in files:
        print(f"  {f['name']}  |  size: {f.get('size', 'N/A')} bytes  |  modified: {f['modifiedTime']}")


    # ================================================================================
    # download filtered files into memory as BytesIO objects
    # ================================================================================
    raw_files = {}


    for f in files:
        file_id = f["id"]
        filename = f["name"]


        request = service.files().get_media(fileId=file_id)
        buffer = io.BytesIO()
        downloader = MediaIoBaseDownload(buffer, request)
        done = False
        while not done:
            _, done = downloader.next_chunk()


        buffer.seek(0)
        raw_files[filename] = buffer
        print(f"Downloaded into memory: {filename}")


    print(f"\nTotal files in memory: {len(raw_files)}")
    clts.elapt[f"Files downloaded: {len(raw_files)}"] = clts.deltat(tstart)


    if not raw_files:
        print("No files found for the selected date window. Nothing to process.")
        return


    # ================================================================================
    # load dblist - pipeline writes to every database listed here
    # ================================================================================
    dblist = get_secret_json(f"{user}-dblist.json")
    dblist = [db for db in dblist if db in ("crate", "tidb")]
    print("dblist:", dblist)


    # ================================================================================
    # execution summary counters
    # ================================================================================
    files_found_count = len(files)
    files_downloaded_count = len(raw_files)
    files_skipped_by_hash_count = 0
    files_to_process_count = 0
    files_parsed_count = 0


    balcao_digital_rows_checked = None
    balcao_digital_rows_inserted = 0
    balcao_digital_rows_skipped = 0
    balcao_consumo_rows_checked = None
    balcao_consumo_rows_inserted = 0
    balcao_consumo_rows_skipped = 0


    row_level_check_executed = False


    # ================================================================================
    # file-level audit check
    # the goal is to process files that are still missing in at least one database
    # ================================================================================
    files_to_process_global = {}
    files_to_process_by_db = {db: set() for db in dblist}
    file_audit_rows = {}
    skipped_by_hash_by_db = {db: [] for db in dblist}


    for db in dblist:
        print(f"\n--- FILE AUDIT CHECK START [{db}] ---")


        connection = None
        cursor = None
        db_engine = None


        try:
            clts.elapt[f"Connecting to database [{db}]"] = clts.deltat(tstart)
            connection, cursor, db_engine, dbcreds = open_database_connection(user, db)
            clts.elapt[f"... connected to {db}"] = clts.deltat(tstart)


            for filename, buffer in raw_files.items():
                try:
                    buffer.seek(0)
                    file_bytes = buffer.getvalue()


                    audit_row = prepare_file_audit(
                        filename=filename,
                        source="google_drive",
                        file_bytes=file_bytes
                    )


                    print(f"[AUDIT][{db}] filename={filename}")
                    print(f"[AUDIT][{db}] hash={audit_row['file_hash']}")


                    already_processed = file_hash_exists(connection, audit_row["file_hash"])


                    if already_processed:
                        print(f"[AUDIT][{db}] SKIPPED already processed file: {filename}")
                        skipped_by_hash_by_db[db].append(filename)
                        continue


                    print(f"[AUDIT][{db}] NEW file, will continue to parsing: {filename}")
                    files_to_process_by_db[db].add(filename)


                    # keep file globally if it is new in at least one database
                    if filename not in files_to_process_global:
                        file_audit_rows[filename] = audit_row
                        files_to_process_global[filename] = io.BytesIO(file_bytes)


                except Exception as e:
                    print(f"[AUDIT][{db}] Error preparing audit for {filename}: {e}")
                    clts.elapt[f"Error preparing audit for {filename} [{db}]: {e}"] = clts.deltat(tstart)


        except Exception as e:
            print(f"Error connecting to {db}: {e}")
            clts.elapt[f"... error connecting [{db}]: {e}"] = clts.deltat(tstart)


        finally:
            print(f"Connection closing.... [{db}]")
            if connection is not None:
                connection.close()
                clts.elapt[f"... database connection closed [{db}]"] = clts.deltat(tstart)


        print(f"--- FILE AUDIT CHECK END [{db}] ---")


    # files skipped by hash only if skipped in all databases
    if dblist:
        skipped_in_all = set(raw_files.keys())
        for db in dblist:
            skipped_in_all = skipped_in_all.intersection(set(skipped_by_hash_by_db.get(db, [])))
        files_skipped_by_hash_count = len(skipped_in_all)
    else:
        files_skipped_by_hash_count = 0


    files_to_process_count = len(files_to_process_global)


    print("\n--- FILE AUDIT GLOBAL SUMMARY ---")
    print(f"Files skipped by hash in all databases: {files_skipped_by_hash_count}")
    print(f"Files to process after file-level audit: {files_to_process_count} / {len(raw_files)}")
    for db in dblist:
        clts.elapt[f"Files skipped by hash [{db}]"] = clts.deltat(tstart)
        clts.elapt[f"Files pending for [{db}]"] = clts.deltat(tstart)


    # ================================================================================
    # parse files once — detect type A or B by column content
    # Type A: potência (Potência Ativa / Reativa)   → balcao_digital
    # Type B: consumo registado (kW)                → balcao_digital_consumo
    # skiprows is auto-detected (tries 8 then 9)
    # CPE is extracted from the filename: Consumos_<CPE>_<timestamp>.xlsx
    # ================================================================================
    parsed_files_map = {}
    skipped_files = []
    processed_files = []


    if files_to_process_global:
        row_level_check_executed = True


        for filename, buffer in files_to_process_global.items():
            try:
                file_type, df, cpe = parse_balcao_file(filename, buffer)
                parsed_files_map[filename] = {
                    "file_type": file_type,
                    "df": df,
                    "cpe": cpe,
                }
                processed_files.append(filename)
                files_parsed_count += 1


                clts.elapt[f"{filename} parsed (Type {file_type}): {len(df)} records"] = clts.deltat(tstart)
                print(f"{filename}: {len(df)} rows | Type {file_type} | CPE: {cpe}")


            except Exception as e:
                print(f"Error parsing {filename}: {e}")
                skipped_files.append(filename)
                clts.elapt[f"Error parsing {filename}: {e}"] = clts.deltat(tstart)


    clts.elapt["All files parsed"] = clts.deltat(tstart)


    total_a = sum(len(item["df"]) for item in parsed_files_map.values() if item["file_type"] == "A")
    total_b = sum(len(item["df"]) for item in parsed_files_map.values() if item["file_type"] == "B")


    print(f"\nType A (potência):  {total_a:,} rows" if total_a else "Type A: 0 rows")
    print(f"Type B (consumo):   {total_b:,} rows" if total_b else "Type B: 0 rows")
    if skipped_files:
        print(f"Skipped files ({len(skipped_files)}): {skipped_files}")


    # ================================================================================
    # insert into every database in dblist
    # id = cpe + tstamp (YYYYMMDDHHMM, no seconds) — consistent with historical data
    # batching avoids statement_max_length limits
    # ================================================================================
    for db in dblist:
        print(f"\n================ INSERTING INTO [{db}] ================")


        connection = None
        cursor = None
        db_engine = None


        try:
            clts.elapt[f"Connecting to database [{db}]"] = clts.deltat(tstart)
            connection, cursor, db_engine, dbcreds = open_database_connection(user, db)
            clts.elapt[f"... connected to {db}"] = clts.deltat(tstart)


            db_files = [f for f in processed_files if f in files_to_process_by_db[db]]
            print(f"Files to insert into [{db}]: {len(db_files)}")


            df_db_a_list = [parsed_files_map[f]["df"] for f in db_files if parsed_files_map[f]["file_type"] == "A"]
            df_db_b_list = [parsed_files_map[f]["df"] for f in db_files if parsed_files_map[f]["file_type"] == "B"]


            df_db_a = pd.concat(df_db_a_list, ignore_index=True) if df_db_a_list else pd.DataFrame()
            df_db_b = pd.concat(df_db_b_list, ignore_index=True) if df_db_b_list else pd.DataFrame()


            if not df_db_a.empty:
                before_a = len(df_db_a)
                df_db_a = df_db_a.drop_duplicates(subset=["id"], keep="first").copy()
                print(f"[DEDUP][{db}] balcao_digital: {before_a} -> {len(df_db_a)}")


            if not df_db_b.empty:
                before_b = len(df_db_b)
                df_db_b = df_db_b.drop_duplicates(subset=["id"], keep="first").copy()
                print(f"[DEDUP][{db}] balcao_digital_consumo: {before_b} -> {len(df_db_b)}")


            for table, df_insert in [
                ("balcao_digital", df_db_a),
                ("balcao_digital_consumo", df_db_b)
            ]:
                if df_insert.empty:
                    print(f"No data for {table} [{db}], skipping.")
                    continue


                clts.elapt[f"Processing {table} [{db}]"] = clts.deltat(tstart)


                all_ids = df_insert["id"].tolist()
                existing_ids = fetch_existing_ids_in_batches(cursor, table, all_ids)
                clts.elapt[f"... {len(existing_ids)} existing records fetched from {table} [{db}]"] = clts.deltat(tstart)


                values_to_insert, skipped, skipped_list = build_values_to_insert(
                    table=table,
                    df_insert=df_insert,
                    existing_ids=existing_ids
                )
                inserts = len(values_to_insert)


                if values_to_insert:
                    sql = get_insert_sql(table, db_engine)
                    cursor.executemany(sql, values_to_insert)
                    connection.commit()


                    # TIDB: REFRESH TABLE only exists in CrateDB
                    if db_engine == "crate":
                        cursor.execute(f"REFRESH TABLE {table}")


                # keep summary like before (using latest successful run values)
                if table == "balcao_digital":
                    balcao_digital_rows_checked = len(df_insert)
                    balcao_digital_rows_inserted = inserts
                    balcao_digital_rows_skipped = skipped
                else:
                    balcao_consumo_rows_checked = len(df_insert)
                    balcao_consumo_rows_inserted = inserts
                    balcao_consumo_rows_skipped = skipped


                clts.elapt[f"... {inserts} inserted, {skipped} skipped @ {table} [{db}]"] = clts.deltat(tstart)
                print(f"... {inserts} inserted, {skipped} skipped @ {table} [{db}]")
                if skipped_list:
                    print(
                        f"... skipped timestamps @ {table} [{db}]: " + ", ".join(skipped_list[:10]) +
                        (f" ... +{len(skipped_list)-10} more" if len(skipped_list) > 10 else "")
                    )


            # ================================================================================
            # insert processed files into file_audit after successful processing
            # only for files that were actually pending in this database
            # ================================================================================
            for filename in db_files:
                try:
                    audit_row = file_audit_rows.get(filename)
                    if audit_row:
                        insert_file_audit_row(connection, audit_row)
                        print(f"[AUDIT][{db}] inserted into file_audit: {filename}")
                        clts.elapt[f"Audit inserted for {filename} [{db}]"] = clts.deltat(tstart)
                except Exception as e:
                    print(f"Error inserting audit row for {filename} [{db}]: {e}")
                    clts.elapt[f"Error inserting audit row for {filename} [{db}]: {e}"] = clts.deltat(tstart)


            if db_files:
                # TIDB: REFRESH TABLE only exists in CrateDB
                if db_engine == "crate":
                    cursor.execute("REFRESH TABLE file_audit")


        except Exception as e:
            print(f"Error inserting into {db}: {e}")
            clts.elapt[f"Error inserting into {db}: {e}"] = clts.deltat(tstart)


        finally:
            print(f"Connection closing.... [{db}]")
            if connection is not None:
                connection.close()
                clts.elapt[f"... database connection closed after insert [{db}]"] = clts.deltat(tstart)


    # ================================================================================
    # final execution summary
    # ================================================================================
    print("\n--- FINAL EXECUTION SUMMARY ---")
    print(f"Files found: {files_found_count}")
    print(f"Files downloaded: {files_downloaded_count}")
    print(f"Files skipped by hash: {files_skipped_by_hash_count}")
    print(f"Files sent to parsing: {files_to_process_count}")
    print(f"Files parsed successfully: {files_parsed_count}")
    print(f"Rows inserted @ balcao_digital: {balcao_digital_rows_inserted}")
    print(f"Rows inserted @ balcao_digital_consumo: {balcao_consumo_rows_inserted}")


    # ================================================================================
    # send profiling email
    # ================================================================================
    clts.elapt["Overall (before email):"] = clts.deltat(tstart)


    if send_mail and email_addresses:
        toem = clts.listtimes()


        summary_rows_html = build_summary_rows_html(
            files_found_count=files_found_count,
            files_downloaded_count=files_downloaded_count,
            files_skipped_by_hash_count=files_skipped_by_hash_count,
            files_to_process_count=files_to_process_count,
            files_parsed_count=files_parsed_count,
            row_level_check_executed=row_level_check_executed,
            balcao_digital_rows_checked=balcao_digital_rows_checked,
            balcao_digital_rows_inserted=balcao_digital_rows_inserted,
            balcao_digital_rows_skipped=balcao_digital_rows_skipped,
            balcao_consumo_rows_checked=balcao_consumo_rows_checked,
            balcao_consumo_rows_inserted=balcao_consumo_rows_inserted,
            balcao_consumo_rows_skipped=balcao_consumo_rows_skipped
        )


        toem = inject_summary_into_existing_notification_table(toem, summary_rows_html)


        if env == "colab":
            notebook_link_html = "<p><a href='[URL_DO_NOTEBOOK]'>&#128211; Abrir notebook no Colab</a></p>"
        else:
            notebook_link_html = ""


        html = f"""
        <html>
            <body style='font-family:Montserrat;'>
                {notebook_link_html}
                <hr color='orange'>
                {toem}
                <hr color='orange'>
                This message is an automated notification from {context}
            </body>
        </html>
        """


        if env == "render":
            try:
                import resend
                resend.api_key = os.getenv("RESEND_API_KEY")
                resend.Emails.send({
                    "from": "onboarding@resend.dev",
                    "to": email_addresses,
                    "subject": context,
                    "html": html
                })
                print("Notification sent.")
                clts.elapt["After sending email"] = clts.deltat(tstart)
            except Exception as e:
                print("Notification not sent:", e)
                clts.elapt[f"email not sent ({e})"] = clts.deltat(tstart)
        else:
            try:
                if env == "colab":
                    credsgmail = json.loads(userdata.get(f"configGMail_{user}.json"))
                else:
                    with open("./secrets/configGMail_ACTC.json", "r") as fh:
                        credsgmail = json.loads(fh.read())


                message = MIMEMultipart("alternative")
                message["Subject"] = context
                message["From"] = credsgmail["UserFrom"]
                message["To"] = ", ".join(email_addresses)


                message.attach(MIMEText(f"This is an automated notification from {context}", "plain"))
                message.attach(MIMEText(html, "html"))


                ssl_context = ssl.create_default_context()
                with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ssl_context) as server:
                    server.login(credsgmail["UserName"], credsgmail["UserPwd"])
                    server.sendmail(credsgmail["UserFrom"], email_addresses, message.as_string())


                print("Notification sent.")
                clts.elapt["After sending email"] = clts.deltat(tstart)


            except Exception as e:
                print("Notification not sent:", e)
                clts.elapt[f"email not sent ({e})"] = clts.deltat(tstart)



if __name__ == "__main__":
    run_pipeline()